filter:
    excluded_paths: ["vendor/*", "tests/*"]

build_failure_conditions:
    - 'elements.rating(<= C).exists'               # No classes/methods with a rating of C or worse
    - 'project.metric("scrutinizer.quality", < 9)' # Code Quality Rating drops below 9
